[package]
authors = ["OKP4"]
edition = "2021"
name = "okp4-cognitarium-client"
version = "5.0.0"

[dependencies]
cosmwasm-std.workspace = true
axone-cognitarium.workspace = true
serde.workspace = true
