[package]
authors = ["OKP4"]
edition = "2021"
name = "okp4-cognitarium-client"
version = "3.0.0"

[dependencies]
cosmwasm-std.workspace = true
okp4-cognitarium.workspace = true
serde.workspace = true
