branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# ØKP4 contracts"
  - - "semantic-release-replace-plugin"
    - replacements:
        - files:
            - contracts/*/Cargo.toml
            - packages/*/Cargo.toml
          from: ^version = "\d+\.\d+\.\d+"$
          to: version = "${nextRelease.version}"
  - - "@semantic-release/exec"
    - prepareCmd: |
        cargo make schema && cargo make docs-generate && cargo make release-assets
  - - "@semantic-release/github"
    - assets:
        - path: "./target/wasm32-unknown-unknown/release/okp4_objectarium.wasm"
        - path: "./target/wasm32-unknown-unknown/release/okp4_law_stone.wasm"
        - path: "./target/wasm32-unknown-unknown/release/okp4_cognitarium.wasm"
        - path: "./target/wasm32-unknown-unknown/release/sha256sum.txt"
        - path: "./contracts/okp4-objectarium/schema/okp4-objectarium.json"
        - path: "./contracts/okp4-law-stone/schema/okp4-law-stone.json"
        - path: "./contracts/okp4-cognitarium/schema/okp4-cognitarium.json"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - contracts/*/Cargo.toml
        - packages/*/Cargo.toml
        - docs/**
        - Cargo.lock
      message: "chore(release): perform release ${nextRelease.version}"
