deny = [
  "unsafe_code",
  "warnings",
  "rust_2018_idioms",
  "trivial_casts",
  "trivial_numeric_casts",
  "unused_lifetimes",
  "unused_import_braces",
  "unused_qualifications",
  "unused_qualifications",
]

warn = []

allow = []
