allow = []

deny = [
  "clippy::complexity",
  "clippy::expect_used",
  "clippy::implicit_clone",
  "clippy::manual_string_new",
  "clippy::map_unwrap_or",
  "clippy::match_same_arms",
  "clippy::option_as_ref_deref",
  "clippy::option_filter_map",
  "clippy::option_map_unit_fn",
  "clippy::or_then_unwrap",
  "clippy::panic",
  "clippy::range_plus_one",
  "clippy::redundant_clone",
  "clippy::redundant_closure_for_method_calls",
  "clippy::semicolon_if_nothing_returned",
  "clippy::single_match_else",
  "clippy::unnecessary_cast",
  "clippy::unnecessary_wraps",
  "clippy::unused_self",
  "clippy::unwrap_used",
  "clippy::useless_asref",
  "clippy::useless_conversion",
  "clippy::useless_format",
  "nonstandard-style",
  "rust_2018_idioms",
  "rust-2021-compatibility",
  "trivial_casts",
  "trivial_numeric_casts",
  "unsafe_code",
  "unused_import_braces",
  "unused_lifetimes",
  "unused_qualifications",
  "warnings",
]

warn = []
