[package]
authors.workspace = true
categories = [
  "cryptography::cryptocurrencies",
  "parser-implementations",
  "data-structures",
]
description = "Package that holds useful components to manage with `CosmWasm` data, typically reading / writing."
documentation = "https://docs.axone.xyz/predicates/open_4#cosmwasm-uri"
edition = "2021"
homepage.workspace = true
license-file.workspace = true
name = "axone-wasm"
readme = "README.md"
repository = "https://github.com/axone-protocol/contracts/tree/main/packages/axone-wasm"
version = "5.0.0"

[dependencies]
cosmwasm-std.workspace = true
form_urlencoded = "1.2.1"
schemars.workspace = true
serde.workspace = true
serde-json-wasm.workspace = true
thiserror.workspace = true
url = "2.5.2"
