[package]
authors = { workspace = true }
edition = { workspace = true }
name = "axone-wasm"

description = "A library that defines CosmWasm URIs, enabling the identification of blockchain resources by referencing specific instantiated smart contracts."
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
form_urlencoded = "1.2.2"
serde.workspace = true
serde-json-wasm.workspace = true
thiserror.workspace = true
url = "2.5.4"
