[package]
authors.workspace = true
categories = ["cryptography::cryptocurrencies"]
description = "Package that holds components to interact with the `axone-objectarium` contract."
documentation = "https://docs.axone.xyz/contracts/okp4-objectarium"
edition = "2021"
homepage.workspace = true
license-file.workspace = true
name = "axone-objectarium-client"
readme = "README.md"
repository = "https://github.com/axone-protocol/contracts/tree/main/packages/axone-objectarium-client"
version = "5.0.0"

[dependencies]
axone-objectarium.workspace = true
axone-wasm.workspace = true
cosmwasm-std.workspace = true
schemars.workspace = true
serde.workspace = true
