[package]
authors = { workspace = true }
edition = { workspace = true }
name = "axone-objectarium-client"

description = "A client library for the Axone Objectarium Smart Contract."
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
axone-objectarium.workspace = true
axone-wasm.workspace = true
cosmwasm-std.workspace = true
serde.workspace = true
