[package]
authors.workspace = true
categories = ["cryptography::cryptocurrencies"]
description = "Package that holds all bindings for querying the AXONE logic module."
documentation = "https://docs.axone.xyz/modules/logic"
edition = "2021"
homepage.workspace = true
license-file.workspace = true
name = "axone-logic-bindings"
readme = "README.md"
repository = "https://github.com/axone-protocol/contracts/tree/main/packages/axone-logic-bindings"
version = "5.0.0"

[dependencies]
axone-wasm.workspace = true
cosmwasm-std.workspace = true
form_urlencoded = "1.2.1"
schemars.workspace = true
serde.workspace = true
serde-json-wasm.workspace = true
thiserror.workspace = true
url = "2.5.2"
