[package]
authors = { workspace = true }
edition = { workspace = true }
name = "axone-logic-bindings"

description = "A library defining the bindings for querying the AXONE logic module."
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-std.workspace = true
schemars.workspace = true
serde.workspace = true
thiserror.workspace = true
