[package]
authors = ["AXONE"]
edition = "2021"
name = "axone-logic-bindings"
version = "6.0.0"

[dependencies]
axone-wasm.workspace = true
cosmwasm-std.workspace = true
form_urlencoded = "1.2.1"
schemars.workspace = true
serde.workspace = true
serde-json-wasm.workspace = true
thiserror.workspace = true
url = "2.5.3"
