[package]
authors = { workspace = true }
edition = { workspace = true }
name = "axone-logic-bindings"

description = "A library defining the bindings for querying the AXONE logic module."
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
axone-wasm.workspace = true
cosmwasm-std.workspace = true
form_urlencoded = "1.2.1"
schemars.workspace = true
serde.workspace = true
serde-json-wasm.workspace = true
thiserror.workspace = true
url = "2.5.4"
