name: Setup Nix
description: Install Nix and enable flakes.

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
