[package]
authors = { workspace = true }
edition = { workspace = true }
name = "axone-cognitarium-client"

description = "A client library for the Axone Cognitarium Smart Contract."
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
axone-cognitarium.workspace = true
cosmwasm-std.workspace = true
serde.workspace = true
