[package]
authors = ["AXONE"]
edition = "2021"
name = "axone-cognitarium-client"
version = "6.0.0"

[dependencies]
axone-cognitarium.workspace = true
cosmwasm-std.workspace = true
serde.workspace = true
