[package]
authors.workspace = true
categories = ["data-structures", "parser-implementations"]
description = "Package that holds useful components to manage with `RDF` data, typically reading / writing."
documentation = "https://docs.axone.xyz/contracts/okp4-cognitarium#model-your-data-with-rdf"
edition = "2021"
homepage.workspace = true
license-file.workspace = true
name = "axone-rdf"
readme = "README.md"
repository = "https://github.com/axone-protocol/contracts/tree/main/packages/axone-rdf"
version = "5.0.0"

[dependencies]
base16ct = { version = "0.2.0", features = ["alloc"] }
cosmwasm-std.workspace = true
itertools = "0.13.0"
rio_api.workspace = true
rio_turtle.workspace = true
rio_xml.workspace = true
sha2 = "0.10.8"
thiserror.workspace = true
