[package]
authors = { workspace = true }
edition = { workspace = true }
name = "axone-rdf"

description = "Utility library offering essential components for efficiently handling RDF data within the Axone protocol."
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
base16ct = { version = "0.2.0", features = ["alloc"] }
cosmwasm-std.workspace = true
itertools = "0.14.0"
rio_api.workspace = true
rio_turtle.workspace = true
rio_xml.workspace = true
sha2 = "0.10.9"
thiserror.workspace = true
