name: Build / WASM

on:
  workflow_call:

  push:
    branches: [main]
    paths:
      - .github/actions/setup-rust/**
      - .github/workflows/build-wasm.yml
      - .cargo/config.toml
      - Cargo.toml
      - Cargo.lock
      - Makefile.toml
      - rust-toolchain.toml
      - contracts/**/*.rs
      - contracts/**/Cargo.toml
      - packages/**/*.rs
      - packages/**/Cargo.toml

  pull_request:
    branches: [main]
    paths:
      - .github/actions/setup-rust/**
      - .github/workflows/build-wasm.yml
      - .cargo/config.toml
      - Cargo.toml
      - Cargo.lock
      - Makefile.toml
      - rust-toolchain.toml
      - contracts/**/*.rs
      - contracts/**/Cargo.toml
      - packages/**/*.rs
      - packages/**/Cargo.toml

concurrency:
  group: build-wasm-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-wasm:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup rust toolchain
        uses: ./.github/actions/setup-rust

      - name: Build wasm
        run: cargo make wasm
