name: Check / README Updated

on:
  workflow_call:

  push:
    branches: [main]
    paths:
      - .github/workflows/check-readme-updated.yml
      - Makefile.toml
      - README.md

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/check-readme-updated.yml
      - Makefile.toml
      - README.md

permissions:
  contents: read

concurrency:
  group: check-readme-updated-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-readme-updated:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Cache cargo registry
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1

      - name: Install cargo make
        uses: davidB/rust-cargo-make@184c522bf8152f601a20749ca36c742b57ba568b # v1

      - name: Generate readme
        run: cargo make readme

      - name: Verify changed readme files
        id: verify-changed-readme-files
        uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf # v20
        with:
          files: |
            README.md

      - name: Run step only when files change.
        if: steps.verify-changed-readme-files.outputs.files_changed == 'true'
        run: |
          echo "❌ README.md has been updated."
          echo "  Changed files : ${{ steps.verify-changed-readme-files.outputs.changed_files }}"
          git diff --name-only | grep 'README.md' | while read -r file; do
            echo "‣ Changes in $file:"
            git diff HEAD "$file"
          done
          echo "Please generate readme using \`cargo make readme\` then commit this new documentation."
          exit 1
