name: Check / Contracts

on:
  workflow_call:

  push:
    branches: [main]
    paths:
      - .github/workflows/check-contracts.yml
      - .github/actions/setup-nix/action.yml
      - .cargo/config.toml
      - Cargo.toml
      - Cargo.lock
      - Makefile.toml
      - rust-toolchain.toml
      - flake.nix
      - flake.lock
      - contracts/**/*.rs
      - contracts/**/Cargo.toml
      - packages/**/*.rs
      - packages/**/Cargo.toml

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/check-contracts.yml
      - .github/actions/setup-nix/action.yml
      - .cargo/config.toml
      - Cargo.toml
      - Cargo.lock
      - Makefile.toml
      - rust-toolchain.toml
      - flake.nix
      - flake.lock
      - contracts/**/*.rs
      - contracts/**/Cargo.toml
      - packages/**/*.rs
      - packages/**/Cargo.toml

permissions:
  contents: read

concurrency:
  group: check-contracts-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-contracts:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Cache cargo registry
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            ~/.rustup
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Check contracts
        run: nix develop -c cargo make check-contracts
