name: Lint / TOML Format

on:
  workflow_call:

  push:
    branches: [main]
    paths:
      - .github/workflows/lint-toml-format.yml
      - .github/actions/setup-nix/action.yml
      - flake.nix
      - flake.lock
      - .taplo.toml
      - '*.toml'
      - '**/*.toml'

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/lint-toml-format.yml
      - .github/actions/setup-nix/action.yml
      - flake.nix
      - flake.lock
      - .taplo.toml
      - '*.toml'
      - '**/*.toml'

permissions:
  contents: read

concurrency:
  group: lint-toml-format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-toml-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Cache cargo registry
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            ~/.rustup
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Check toml files are formatted
        run: |
          nix develop -c cargo make format-toml
          if git status -s | grep -q .toml; then
            >&2 echo "❌ There is a diff between formatted files and source code"
            >&2 git status
            exit 1
          fi
