name: Lint / Cargo Makefile

on:
  workflow_call:

  push:
    branches: [main]
    paths:
      - .github/workflows/lint-cargo-makefile.yml
      - .github/actions/setup-nix/action.yml
      - Makefile.toml
      - flake.nix
      - flake.lock

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/lint-cargo-makefile.yml
      - .github/actions/setup-nix/action.yml
      - Makefile.toml
      - flake.nix
      - flake.lock

permissions:
  contents: read

concurrency:
  group: lint-cargo-makefile-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-cargo-makefile:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Cache cargo registry
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            ~/.rustup
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Lint cargo-make task names
        run: |
          FAILED=0
          for task in $(nix develop -c cargo make --list-all-steps | awk '{print $1;}' | sort | grep -v -- '---' ); do
            if echo "$task" | grep '_' > /dev/null; then
              >&2 echo "❌ $task - use kebab-case style for task names (e.g. 'my-task' instead of 'my_task')"
              FAILED=1
            else
              echo "✅ $task"
            fi
          done
          if [ "${FAILED}" = "1" ]; then
            exit 1
          fi
