name: Lint / Markdown

on:
  workflow_call:

  push:
    branches: [main]
    paths:
      - .github/workflows/lint-markdown.yml
      - .markdownlint.yaml
      - '*.md'
      - '**/*.md'
      - '!**/CHANGELOG.md'
      - '!docs/**/*.md'

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/lint-markdown.yml
      - .markdownlint.yaml
      - '*.md'
      - '**/*.md'
      - '!**/CHANGELOG.md'
      - '!docs/**/*.md'

permissions:
  contents: read

concurrency:
  group: lint-markdown-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Lint markdown files
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1.5.0
        with:
          args: "**/*.md"
          ignore: "CHANGELOG.md docs/**/*.md"
