name: Report / WASM Size

on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/report-wasm-size.yml
      - .cargo/config.toml
      - .github/package.json
      - .size-limit.json
      - Cargo.toml
      - Cargo.lock
      - Makefile.toml
      - rust-toolchain.toml
      - contracts/**/*.rs
      - contracts/**/Cargo.toml
      - packages/**/*.rs
      - packages/**/Cargo.toml

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: report-wasm-size-${{ github.ref }}
  cancel-in-progress: true

jobs:
  report-wasm-size:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Cache cargo registry
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1

      - name: Install cargo make
        uses: davidB/rust-cargo-make@184c522bf8152f601a20749ca36c742b57ba568b # v1

      - name: Prepare size limit
        run: cp .github/package.json package.json

      - name: Report wasm size limit
        uses: andresz1/size-limit-action@94bc357df29c36c8f8d50ea497c3e225c3c95d1d # v1.8.0
        with:
          github_token: ${{ secrets.OPS_TOKEN }}
